name: 'Terraform'

on:
  push:
    branches:
      - 'feat/TerraformActons_test'
    paths:
      - '**.tf'

env:
  TF_LOG: INFO

jobs:
  Terraform-Dev:
    name: 'Deploy in Test'
    runs-on: ubuntu-latest
    environment: Test
    defaults:
      run:
        shell: bash
        working-directory: ./tf/TFProjects/tfDatabricks
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7
    - name: Initializing the Test backend
      id: init
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      run: terraform init -backend-config backend/test.tfvars

    - name: Plan Test
      id: plan
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        TF_VAR_clientid: ${{ secrets.ARM_CLIENT_ID }}
        TF_VAR_clientsecret: ${{ secrets.ARM_CLIENT_SECRET }}
      run: terraform plan -var-file vars/test.tfvars

    - name: Apply Test
      id: Apply
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        TF_VAR_clientid: ${{ secrets.ARM_CLIENT_ID }}
        TF_VAR_clientsecret: ${{ secrets.ARM_CLIENT_SECRET }}
      run: terraform apply -auto-approve -var-file vars/test.tfvars